version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: my_database
    restart: always
    env_file:
      - ./mariadb/tools/.env
    volumes:
      - ./mariadb/conf/60-server.cnf:/etc/mysql/mariadb.conf.d/60-server.cnf
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: my_nginx
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - mariadb
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:

